---

- include_vars: main.yml

- name: Add apt repository for Oracle Java
  become: true
  apt_repository: repo='ppa:webupd8team/java'
  tags:
    - add-java-repo

- name: Accept License Agreement
  become: true
  debconf: name="{{ java_installer_name }}" question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'